#ifndef HISTORYDATA_GLOBAL_H
#define HISTORYDATA_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(HISTORYDATA_LIBRARY)
#  define HISTORYDATASHARED_EXPORT Q_DECL_EXPORT
#else
#  define HISTORYDATASHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // HISTORYDATA_GLOBAL_H
